import os
import io
from datetime import datetime
from fpdf import FPDF
import qrcode

# Languages
LABELS = {
    "en": {
        "title": "Citizen Action Pack",
        "profile": "Your profile",
        "schemes": "Schemes you can apply for",
        "docs": "Documents to collect",
        "apply": "How to apply",
        "csc": "Nearest Common Service Centre",
        "benefit": "Estimated yearly benefit",
        "disclaimer": "Generated by SchemeSetu Bharat. Eligibility is indicative. Always confirm on the official portal.",
        "simulated": "Simulated demo data",
        "name": "Name",
        "district": "District",
        "occupation": "Occupation",
        "income": "Income",
        "land": "Land (ha)",
        "rank": "Rank",
        "scheme_name": "Scheme Name",
        "yearly_benefit": "Yearly Benefit",
        "status": "Status",
        "reasons": "Why you qualify",
        "steps": "Application Steps",
        "portal_url": "Portal URL",
        "address": "Address",
        "phone": "Phone",
        "hours": "Hours"
    },
    "hi": {
        "title": "नागरिक कार्य योजना (Citizen Action Pack)",
        "profile": "आपकी प्रोफाइल (Your Profile)",
        "schemes": "योजनाएं जिनके लिए आप आवेदन कर सकते हैं",
        "docs": "एकत्र करने के लिए दस्तावेज़",
        "apply": "आवेदन कैसे करें",
        "csc": "निकटतम जन सेवा केंद्र (CSC)",
        "benefit": "अनुमानित वार्षिक लाभ",
        "disclaimer": "स्कीमसेतु भारत द्वारा जनरेट किया गया। पात्रता सांकेतिक है। हमेशा आधिकारिक पोर्टल पर पुष्टि करें।",
        "simulated": "सिम्युलेटेड डेमो डेटा",
        "name": "नाम",
        "district": "ज़िला",
        "occupation": "पेशा",
        "income": "आय",
        "land": "भूमि (हेक्टेयर)",
        "rank": "रैंक",
        "scheme_name": "योजना का नाम",
        "yearly_benefit": "वार्षिक लाभ",
        "status": "स्थिति",
        "reasons": "आप क्यों पात्र हैं",
        "steps": "आवेदन के चरण",
        "portal_url": "पोर्टल यूआरएल (URL)",
        "address": "पता",
        "phone": "फ़ोन",
        "hours": "समय"
    },
    "mr": {
        "title": "नागरिक कृती आराखडा (Citizen Action Pack)",
        "profile": "तुमची प्रोफाइल",
        "schemes": "योजना ज्यासाठी तुम्ही अर्ज करू शकता",
        "docs": "गोळा करण्यासाठी कागदपत्रे",
        "apply": "अर्ज कसा करावा",
        "csc": "जवळचे जन सेवा केंद्र (CSC)",
        "benefit": "अंदाजित वार्षिक लाभ",
        "disclaimer": "स्कीमसेतू भारत द्वारे व्युत्पन्न. पात्रता सूचक आहे. नेहमी अधिकृत पोर्टलवर पुष्टी करा.",
        "simulated": "सिम्युलेटेड डेमो डेटा",
        "name": "नाव",
        "district": "जिल्हा",
        "occupation": "व्यवसाय",
        "income": "उत्पन्न",
        "land": "जमीन (हेक्टर)",
        "rank": "रँक",
        "scheme_name": "योजनेचे नाव",
        "yearly_benefit": "वार्षिक लाभ",
        "status": "स्थिती",
        "reasons": "तुम्ही का पात्र आहात",
        "steps": "अर्जाच्या पायऱ्या",
        "portal_url": "पोर्टल URL",
        "address": "पत्ता",
        "phone": "फोन",
        "hours": "वेळ"
    }
}

class ActionPackPDF(FPDF):
    def __init__(self, language="en"):
        super().__init__()
        self.language = language
        if self.language not in LABELS:
            self.language = "en"
        self.labels = LABELS[self.language]
        
    def footer(self):
        self.set_y(-15)
        self.set_font("NotoSans", "", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_action_pack(result: dict, language: str, out_dir: str = "output") -> str:
    if language not in LABELS:
        language = "en"
    lbl = LABELS[language]
    
    os.makedirs(out_dir, exist_ok=True)
    
    pdf = ActionPackPDF(language=language)
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Configure text shaping and fonts
    # pdf.set_text_shaping(True)
    
    # Paths to fonts
    fonts_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "assets", "fonts")
    
    # Add Latin fonts
    pdf.add_font("NotoSans", style="", fname=os.path.join(fonts_dir, "NotoSans-Regular.ttf"))
    pdf.add_font("NotoSans", style="B", fname=os.path.join(fonts_dir, "NotoSans-Bold.ttf"))
    
    # Add Devanagari fonts
    pdf.add_font("NotoSansDevanagari", style="", fname=os.path.join(fonts_dir, "NotoSansDevanagari-Regular.ttf"))
    pdf.add_font("NotoSansDevanagari", style="B", fname=os.path.join(fonts_dir, "NotoSansDevanagari-Bold.ttf"))
    
    # Set fallback for NotoSans to use Devanagari when needed
    pdf.set_fallback_fonts(["NotoSansDevanagari"])
    
    pdf.add_page()
    
    # Tricolour bar at top
    pdf.set_fill_color(255, 153, 51) # Saffron
    pdf.rect(0, 0, pdf.w / 3, 5, style="F")
    pdf.set_fill_color(255, 255, 255) # White
    pdf.rect(pdf.w / 3, 0, pdf.w / 3, 5, style="F")
    pdf.set_fill_color(19, 136, 8) # Green
    pdf.rect(2 * pdf.w / 3, 0, pdf.w / 3, 5, style="F")
    
    pdf.ln(10)
    
    # Title
    pdf.set_font("NotoSans", "B", 24)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, lbl["title"], align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(5)
    
    # Profile
    pdf.set_font("NotoSans", "B", 14)
    pdf.cell(0, 10, lbl["profile"], new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("NotoSans", "", 12)
    profile = result.get("user_profile", {})
    
    name = profile.get("name") or "-"
    district = profile.get("district") or "-"
    occupation = profile.get("occupation") or "-"
    income = str(profile.get("annual_income_inr")) if profile.get("annual_income_inr") is not None else "-"
    land = str(profile.get("land_hectares")) if profile.get("land_hectares") is not None else "-"
    
    pdf.cell(0, 8, f"{lbl['name']}: {name} | {lbl['district']}: {district}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"{lbl['occupation']}: {occupation} | {lbl['income']}: Rs {income} | {lbl['land']}: {land}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(5)
    
    # Benefit Box
    benefit = result.get("total_potential_benefit_inr", 0)
    pdf.set_fill_color(230, 245, 230)
    pdf.set_font("NotoSans", "B", 16)
    pdf.cell(0, 20, f"{lbl['benefit']}: Rs {benefit:,}", border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(5)
    
    # Agent explanation
    summary_key = "vernacular_summary" if language != "en" else "summary_text"
    explanation = result.get(summary_key) or result.get("summary_text", "")
    if explanation:
        pdf.set_font("NotoSans", "", 11)
        pdf.multi_cell(0, 8, explanation)
        pdf.ln(5)
    
    # Schemes Summary
    eligible = result.get("eligible_schemes", [])
    review = result.get("review_schemes", [])
    all_schemes = eligible + review
    
    if all_schemes:
        pdf.set_font("NotoSans", "B", 14)
        pdf.cell(0, 10, lbl["schemes"], new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("NotoSans", "B", 10)
        # Table Header
        col_w = [15, 90, 45, 40]
        pdf.cell(col_w[0], 10, lbl["rank"], border=1)
        pdf.cell(col_w[1], 10, lbl["scheme_name"], border=1)
        pdf.cell(col_w[2], 10, lbl["yearly_benefit"], border=1)
        pdf.cell(col_w[3], 10, lbl["status"], border=1, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("NotoSans", "", 10)
        rank = 1
        for s in all_schemes:
            status_text = s.get("status", "-")
            amt = s.get("benefit_amount_inr", 0)
            pdf.cell(col_w[0], 10, str(rank), border=1)
            pdf.cell(col_w[1], 10, s.get("scheme_name", "-")[:45], border=1)
            pdf.cell(col_w[2], 10, f"Rs {amt:,}", border=1)
            pdf.cell(col_w[3], 10, status_text, border=1, new_x="LMARGIN", new_y="NEXT")
            rank += 1
            
    # ONE PAGE PER SCHEME
    for i, s in enumerate(all_schemes):
        pdf.add_page()
        pdf.set_font("NotoSans", "B", 16)
        pdf.cell(0, 10, f"Scheme {i+1}: {s.get('scheme_name', '-')}", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("NotoSans", "", 12)
        pdf.cell(0, 8, f"{lbl['benefit']}: Rs {s.get('benefit_amount_inr', 0):,} ({s.get('benefit_description', '-')})", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        
        # Reasons
        pdf.set_font("NotoSans", "B", 12)
        pdf.cell(0, 8, lbl["reasons"] + ":", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("NotoSans", "", 11)
        
        # passed_criteria usually string list
        for r in s.get("passed_criteria", []):
            pdf.multi_cell(0, 6, f"- {r}")
            
        pdf.ln(5)
        
        # Documents (empty square for checkbox)
        docs = s.get("required_documents", [])
        if docs:
            pdf.set_font("NotoSans", "B", 12)
            pdf.cell(0, 8, lbl["docs"] + ":", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("NotoSans", "", 11)
            for d in docs:
                # Draw small rect
                x = pdf.get_x()
                y = pdf.get_y()
                pdf.rect(x + 2, y + 1, 4, 4)
                pdf.set_x(x + 8)
                pdf.multi_cell(0, 6, d)
            pdf.ln(5)
            
        # Steps
        steps = [
            f"Visit the portal: {s.get('portal_url', 'N/A')}",
            "Register or login using Aadhaar / Mobile number",
            "Fill out the application form",
            "Upload the required documents listed above",
            "Submit the application and note the reference number"
        ]
        
        pdf.set_font("NotoSans", "B", 12)
        pdf.cell(0, 8, lbl["steps"] + ":", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("NotoSans", "", 11)
        for idx, step in enumerate(steps, 1):
            pdf.multi_cell(0, 6, f"{idx}. {step}")
            
        pdf.ln(10)
        
        # QR Code
        url = s.get("portal_url")
        if url and url != "N/A" and url.startswith("http"):
            pdf.set_font("NotoSans", "B", 12)
            pdf.cell(0, 8, lbl["portal_url"] + ":", new_x="LMARGIN", new_y="NEXT")
            
            # Clickable link
            pdf.set_font("NotoSans", "U", 11)
            pdf.set_text_color(0, 0, 255)
            pdf.cell(0, 6, url, link=url, new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            
            # Generate QR
            qr = qrcode.QRCode(box_size=4, border=2)
            qr.add_data(url)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            
            # Save to in-memory bytes
            img_byte_arr = io.BytesIO()
            img.save(img_byte_arr, format='PNG')
            
            pdf.image(img_byte_arr, w=40)
            
    # Final Page (CSC & Disclaimer)
    pdf.add_page()
    pdf.set_font("NotoSans", "B", 16)
    pdf.cell(0, 10, lbl["csc"], new_x="LMARGIN", new_y="NEXT")
    
    csc = result.get("csc_recommendation")
    if csc:
        if csc.get("simulated") or result.get("simulated", True):
            pdf.set_font("NotoSans", "B", 10)
            pdf.set_text_color(255, 0, 0)
            pdf.cell(0, 8, lbl["simulated"], new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            
        pdf.set_font("NotoSans", "", 12)
        pdf.cell(0, 8, f"{lbl['name']}: {csc.get('center_name', '-')}", new_x="LMARGIN", new_y="NEXT")
        pdf.multi_cell(0, 8, f"{lbl['address']}: {csc.get('address', '-')}")
        pdf.cell(0, 8, f"{lbl['phone']}: {csc.get('contact_phone', '-')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 8, f"{lbl['hours']}: {csc.get('operating_hours', '-')}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("NotoSans", "", 12)
        pdf.cell(0, 8, "No CSC details available.", new_x="LMARGIN", new_y="NEXT")
        
    pdf.ln(20)
    pdf.set_font("NotoSans", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, lbl["disclaimer"])
    
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    name_clean = name.replace(" ", "_").lower() if name != "-" else "citizen"
    filename = f"action_pack_{name_clean}_{ts}_{language}.pdf"
    filepath = os.path.join(out_dir, filename)
    
    pdf.output(filepath)
    return filepath
